#!/usr/bin/python3

import gi
gi.require_version('Notify', '0.7')

from gi.repository import Notify

import daemonize
import os
import requests
import time
import webbrowser

print('Starting miniflux notifier on', os.environ['MINIFLUX_URL'])

cache = {'total': 0, 'entry_ids': set([])}
Notify.init('miniflux-notifier')
pid = '/tmp/miniflux-notifier.pid'

def main():
  while True:
    print('Polling...')
    r = requests.get(os.environ['MINIFLUX_URL'] + '/v1/entries?status=unread&direction=desc', auth=(os.environ['MINIFLUX_USER'], os.environ['MINIFLUX_PASS']))
    payload = r.json()
    entry_ids = set([entry['id'] for entry in payload['entries']])
    new_ids = list(entry_ids - cache['entry_ids'])

    if len(new_ids) > 0:
      print('Found new IDs:', new_ids)
      cache['entry_ids'] = entry_ids
      first = payload['entries'][0]['title']
      others = ' +' + str(len(new_ids) - 1) if len(new_ids) > 1 else ''
      notification = Notify.Notification.new('Miniflux: New Article' + others, first)
      notification.show()
    else:
      print('Nothing new.')

    time.sleep(os.environ.get('MINIFLUX_PERIOD', 300))

daemon = daemonize.Daemonize(app='miniflux_notifier', pid=pid, action=main)
daemon.start()
